const customers = [
  {
    id: "CUST-001",
    name: "Ashley Wilson",
    email: "ashley.wilson@example.com",
    phone: "+1 (555) 123-4567",
    registrationDate: new Date(2025, 2, 10),
    totalReservations: 3,
    totalSpent: 2580,
    lastReservation: new Date(2025, 2, 8),
  },
  {
    id: "CUST-002",
    name: "James Thompson",
    email: "james.t@example.com",
    phone: "+1 (555) 987-6543",
    registrationDate: new Date(2025, 2, 8),
    totalReservations: 1,
    totalSpent: 1200,
    lastReservation: new Date(2025, 2, 8),
  },
  {
    id: "CUST-003",
    name: "Sarah Lee",
    email: "sarah.lee@example.com",
    phone: "+1 (555) 456-7890",
    registrationDate: new Date(2025, 2, 7),
    totalReservations: 2,
    totalSpent: 1850,
    lastReservation: new Date(2025, 2, 5),
  },
  {
    id: "CUST-004",
    name: "Robert Johnson",
    email: "robert.j@example.com",
    phone: "+1 (555) 234-5678",
    registrationDate: new Date(2025, 2, 5),
    totalReservations: 5,
    totalSpent: 4200,
    lastReservation: new Date(2025, 2, 1),
  },
  {
    id: "CUST-005",
    name: "Emily Davis",
    email: "emily.d@example.com",
    phone: "+1 (555) 876-5432",
    registrationDate: new Date(2025, 2, 3),
    totalReservations: 2,
    totalSpent: 1500,
    lastReservation: new Date(2025, 1, 28),
  },
  {
    id: "CUST-006",
    name: "Michael Brown",
    email: "michael.b@example.com",
    phone: "+1 (555) 345-6789",
    registrationDate: new Date(2025, 2, 1),
    totalReservations: 1,
    totalSpent: 750,
    lastReservation: new Date(2025, 2, 1),
  },
  {
    id: "CUST-007",
    name: "Jennifer Garcia",
    email: "jennifer.g@example.com",
    phone: "+1 (555) 567-8901",
    registrationDate: new Date(2025, 1, 28),
    totalReservations: 3,
    totalSpent: 2100,
    lastReservation: new Date(2025, 1, 25),
  },
  {
    id: "CUST-008",
    name: "David Martinez",
    email: "david.m@example.com",
    phone: "+1 (555) 678-9012",
    registrationDate: new Date(2025, 1, 25),
    totalReservations: 2,
    totalSpent: 1800,
    lastReservation: new Date(2025, 1, 20),
  },
  {
    id: "CUST-009",
    name: "Lisa Rodriguez",
    email: "lisa.r@example.com",
    phone: "+1 (555) 789-0123",
    registrationDate: new Date(2025, 1, 20),
    totalReservations: 4,
    totalSpent: 3200,
    lastReservation: new Date(2025, 1, 15),
  },
  {
    id: "CUST-010",
    name: "Kevin Wilson",
    email: "kevin.w@example.com",
    phone: "+1 (555) 890-1234",
    registrationDate: new Date(2025, 1, 15),
    totalReservations: 1,
    totalSpent: 950,
    lastReservation: new Date(2025, 1, 15),
  },
];

// Sample data for customer concerns
const concerns = [
  {
    id: "CONC-001",
    customerId: "CUST-001",
    customerName: "Ashley Wilson",
    message: "Can you confirm delivery by 7 PM for our event this Saturday?",
    submittedAt: new Date(2025, 2, 9, 10, 30),
    status: "Open",
    isRegistered: true,
  },
  {
    id: "CONC-002",
    customerId: "CUST-004",
    customerName: "Robert Johnson",
    message:
      "Need to add 5 more vegetarian meals to our corporate lunch order for next week.",
    submittedAt: new Date(2025, 2, 9, 8, 15),
    status: "Open",
    isRegistered: true,
  },
  {
    id: "CONC-003",
    customerId: null,
    customerName: "Guest",
    message:
      "Do you offer gluten-free options for your birthday packages? I have several guests with dietary restrictions.",
    submittedAt: new Date(2025, 2, 8, 14, 45),
    status: "Open",
    isRegistered: false,
  },
  {
    id: "CONC-004",
    customerId: "CUST-007",
    customerName: "Jennifer Garcia",
    message:
      "Need to reschedule our family reunion catering from April 10 to April 17. Is this possible?",
    submittedAt: new Date(2025, 2, 7, 16, 20),
    status: "Open",
    isRegistered: true,
  },
  {
    id: "CONC-005",
    customerId: "CUST-002",
    customerName: "James Thompson",
    message:
      "I'd like to upgrade our beverage package to include premium wines. What are the options?",
    submittedAt: new Date(2025, 2, 6, 11, 10),
    status: "Resolved",
    isRegistered: true,
  },
  {
    id: "CONC-006",
    customerId: null,
    customerName: "Guest",
    message:
      "What's your cancellation policy? We might need to cancel our event due to unforeseen circumstances.",
    submittedAt: new Date(2025, 2, 5, 9, 30),
    status: "Resolved",
    isRegistered: false,
  },
  {
    id: "CONC-007",
    customerId: "CUST-009",
    customerName: "Lisa Rodriguez",
    message:
      "Can we get a detailed breakdown of costs for our upcoming event? Need it for our accounting department.",
    submittedAt: new Date(2025, 2, 4, 13, 45),
    status: "Resolved",
    isRegistered: true,
  },
  {
    id: "CONC-008",
    customerId: "CUST-005",
    customerName: "Emily Davis",
    message:
      "One of our guests has a severe nut allergy. Can you ensure all dishes are nut-free?",
    submittedAt: new Date(2025, 2, 3, 15, 20),
    status: "Resolved",
    isRegistered: true,
  },
];

export { customers, concerns };
