import { PaymentType } from "@/types/component-types";

// Sample data for payments
export const payments: PaymentType[] = [
  {
    id: "PAY-001",
    reservationId: "RES-1234",
    customer: {
      name: "Ashley Wilson",
      email: "ashley.wilson@example.com",
      phone: "+1 (555) 123-4567",
      isRegistered: true,
    },
    amount: 2580,
    status: "Paid",
    paymentDate: new Date(2025, 2, 5),
    paymentMethod: "Credit Card",
    createdDate: new Date(2025, 2, 1),
    reservation: {
      eventDate: new Date(2025, 2, 10),
      address: "123 Wedding Venue, Springfield, IL",
      items: [
        { name: "Wedding Package - Premium", quantity: 1, price: 2000 },
        { name: "Additional Appetizers", quantity: 3, price: 180 },
        { name: "Champagne Toast", quantity: 1, price: 400 },
      ],
    },
    isUrgent: false,
  },
  {
    id: "PAY-002",
    reservationId: "RES-1235",
    customer: {
      name: "Tech Inc.",
      email: "events@techinc.com",
      phone: "+1 (555) 987-6543",
      isRegistered: true,
    },
    amount: 1200,
    status: "Paid",
    paymentDate: new Date(2025, 2, 7),
    paymentMethod: "Bank Transfer",
    createdDate: new Date(2025, 2, 3),
    reservation: {
      eventDate: new Date(2025, 2, 11),
      address: "456 Tech Inc. HQ, Springfield, IL",
      items: [
        { name: "Corporate Lunch Package", quantity: 1, price: 900 },
        { name: "Premium Dessert Platter", quantity: 2, price: 300 },
      ],
    },
    isUrgent: false,
  },
  {
    id: "PAY-003",
    reservationId: "RES-1236",
    customer: {
      name: "Smith Family",
      email: "john.smith@example.com",
      phone: "+1 (555) 456-7890",
      isRegistered: true,
    },
    amount: 950,
    status: "Pending",
    paymentDate: null,
    paymentMethod: null,
    createdDate: new Date(2025, 2, 4),
    reservation: {
      eventDate: new Date(2025, 2, 14),
      address: "789 Community Center, Springfield, IL",
      items: [
        { name: "Family Gathering Package", quantity: 1, price: 750 },
        { name: "Additional Sides", quantity: 4, price: 200 },
      ],
    },
    isUrgent: false,
  },
  {
    id: "PAY-004",
    reservationId: "RES-1237",
    customer: {
      name: "Guest Order",
      email: "maria@example.com",
      phone: "+1 (555) 234-5678",
      isRegistered: false,
    },
    amount: 350,
    status: "Pending",
    paymentDate: null,
    paymentMethod: null,
    createdDate: new Date(2025, 2, 5),
    reservation: {
      eventDate: new Date(2025, 2, 15),
      address: "101 Residential St, Springfield, IL",
      items: [
        { name: "Dinner Party Package - Basic", quantity: 1, price: 300 },
        { name: "Specialty Drinks", quantity: 10, price: 50 },
      ],
    },
    isUrgent: true,
  },
  {
    id: "PAY-005",
    reservationId: "RES-1238",
    customer: {
      name: "Johnson Wedding",
      email: "johnson.wedding@example.com",
      phone: "+1 (555) 876-5432",
      isRegistered: true,
    },
    amount: 3200,
    status: "Paid",
    paymentDate: new Date(2025, 1, 20),
    paymentMethod: "Credit Card",
    createdDate: new Date(2025, 1, 15),
    reservation: {
      eventDate: new Date(2025, 3, 5),
      address: "200 Elegant Venue, Springfield, IL",
      items: [
        { name: "Wedding Package - Deluxe", quantity: 1, price: 2800 },
        { name: "Premium Bar Service", quantity: 1, price: 400 },
      ],
    },
    isUrgent: false,
  },
  {
    id: "PAY-006",
    reservationId: "RES-1239",
    customer: {
      name: "Community Center",
      email: "events@communitycenter.org",
      phone: "+1 (555) 345-6789",
      isRegistered: true,
    },
    amount: 1500,
    status: "Paid",
    paymentDate: new Date(2025, 2, 1),
    paymentMethod: "Check",
    createdDate: new Date(2025, 1, 25),
    reservation: {
      eventDate: new Date(2025, 2, 20),
      address: "300 Community Way, Springfield, IL",
      items: [
        { name: "Community Event Package", quantity: 1, price: 1200 },
        { name: "Additional Appetizers", quantity: 5, price: 300 },
      ],
    },
    isUrgent: false,
  },
  {
    id: "PAY-007",
    reservationId: "RES-1240",
    customer: {
      name: "Birthday Celebration",
      email: "birthday@example.com",
      phone: "+1 (555) 567-8901",
      isRegistered: false,
    },
    amount: 750,
    status: "Pending",
    paymentDate: null,
    paymentMethod: null,
    createdDate: new Date(2025, 2, 8),
    reservation: {
      eventDate: new Date(2025, 2, 25),
      address: "400 Party Place, Springfield, IL",
      items: [
        { name: "Birthday Package - Standard", quantity: 1, price: 600 },
        { name: "Custom Cake", quantity: 1, price: 150 },
      ],
    },
    isUrgent: false,
  },
  {
    id: "PAY-008",
    reservationId: "RES-1241",
    customer: {
      name: "Corporate Training",
      email: "training@corporation.com",
      phone: "+1 (555) 678-9012",
      isRegistered: true,
    },
    amount: 900,
    status: "Paid",
    paymentDate: new Date(2025, 2, 5),
    paymentMethod: "Credit Card",
    createdDate: new Date(2025, 2, 1),
    reservation: {
      eventDate: new Date(2025, 3, 2),
      address: "500 Corporate Blvd, Springfield, IL",
      items: [{ name: "All-Day Corporate Package", quantity: 1, price: 900 }],
    },
    isUrgent: false,
  },
  {
    id: "PAY-009",
    reservationId: "RES-1242",
    customer: {
      name: "Retirement Party",
      email: "retirement@example.com",
      phone: "+1 (555) 789-0123",
      isRegistered: false,
    },
    amount: 1100,
    status: "Pending",
    paymentDate: null,
    paymentMethod: null,
    createdDate: new Date(2025, 2, 7),
    reservation: {
      eventDate: new Date(2025, 3, 10),
      address: "600 Garden Venue, Springfield, IL",
      items: [
        { name: "Celebration Package", quantity: 1, price: 850 },
        { name: "Premium Wine Selection", quantity: 1, price: 250 },
      ],
    },
    isUrgent: true,
  },
  {
    id: "PAY-010",
    reservationId: "RES-1243",
    customer: {
      name: "Charity Gala",
      email: "gala@charity.org",
      phone: "+1 (555) 890-1234",
      isRegistered: true,
    },
    amount: 5000,
    status: "Paid",
    paymentDate: new Date(2025, 1, 15),
    paymentMethod: "Bank Transfer",
    createdDate: new Date(2025, 1, 10),
    reservation: {
      eventDate: new Date(2025, 3, 15),
      address: "700 Grand Hall, Springfield, IL",
      items: [
        { name: "Gala Package - Premium", quantity: 1, price: 4500 },
        { name: "Specialty Dessert Station", quantity: 1, price: 500 },
      ],
    },
    isUrgent: false,
  },
];

// Current date for reference
export const currentDate = new Date(2025, 2, 9);
